robots:
  - id: 0
    type: open_chain
    driver_ids: [0, 1]
    home_joint_position: [0.0, 45.0] 
    base_configuration:
      position: [0.0, 0.0, 0.0] 
      orientation: [0.0, 0.0, 0.0] 
    home_configuration:
      position: [0.0, 0.0, 0.0] 
      orientation: [0.0, 0.0, 0.0] 
    target_configuration:
      - position: [0.0, 0.0, 0.0] 
        orientation: [0.0, 0.0, 0.0] 
      - position: [0.0, 0.0, 0.0] 
        orientation: [0.0, 0.0, 0.0] 
    screw_axes:
      - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
    self_collision:
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 0.0]
    obstacle_ids: [0, 10, 11, 12, 13, 14, 15, 16, 17, 18]

  - id: 1
    type: open_chain
    driver_ids: [2, 3]
    home_joint_position: [0.0, -45.0]
    base_configuration:
      position: [0.0, 0.0, 0.0] 
      orientation: [0.0, 0.0, 0.0] 
    home_configuration:
      position: [0.0, 0.0, 0.0] 
      orientation: [0.0, 0.0, 0.0] 
    target_configuration:
      - position: [0.0, 0.0, 0.0] 
        orientation: [0.0, 0.0, 0.0] 
      - position: [0.0, 0.0, 0.0] 
        orientation: [0.0, 0.0, 0.0] 
    screw_axes:
      - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
    self_collision:
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0] 
      - [0.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 0.0]
    obstacle_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]